### ISSUE TITLE
Solid widget hard codes the solid.community popup, which is now down

### ISSUE THREAD

**Issue by almereyda** [bourgeoa/tiddlywiki-node-solid-server#7]
The login form tries to open solid.community, which has [recently shut down](https://gitlab.com/solid.community/proposals/-/issues/16), even when entering a pod on the new home of its data, like `https://yala.solidcommunity.net`.

**Comment by bourgeoa** [comment]
Sorry for the delay everything as been upgraded to v1.0.0 : 
- uses solidcommunity.net by default
- upgraded to 
 -- solid-file-widget v1.0.0
 -- solid-file-client v1.1.0
 -- solid-auth-client v2.5.2

All tiddlers are saved as .ttl files in your pod.
If you were using an old version saving tiddlers as .json, you shall be proposed a migration with a backup

**Comment by almereyda** [comment]
Thanks a lot! This is not a great delay, given the ecosystem effect such an upstream change has.

After creating the tiddlers folder manually, TiddlyWiki could connect to my pod, but then throws:

> Cannot access https://yala.solidcommunity.net/public/tiddlers/main
> SFCFetchError: SFCFetchError 403 https://yala.solidcommunity.net/public/tiddlers/ - Make sure that the origin of your app is authorized for your pod

in a modal.

**Comment by almereyda** [comment]
Then when dismissing that dialogue, typing in a title and trying nevertheless, it throws

> Error saved tiddler : SFCFetchError: SFCFetchError 404 https://yala.solidcommunity.net/public/tiddlers/main/ - The requested resource could not be found

Is there some kind of bootstrap process involved that breaks here, which produces the requested and missing LDP containers, before the app actually uses them?

**Comment by almereyda** [comment]
When saving GettingStarted with my details, it throws a red modal that reads

> Internal JavaScript Error
> Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
> TypeError: path is undefined

**Comment by bourgeoa** [comment]
> After creating the tiddlers folder manually, TiddlyWiki could connect to my pod, but then throws:
> 
> > Cannot access https://yala.solidcommunity.net/public/tiddlers/main
> > SFCFetchError: SFCFetchError 403 https://yala.solidcommunity.net/public/tiddlers/ - Make sure that the origin of your app is authorized for your pod
> 
> in a modal.

This means that the app is not authorized by your pod. You need to add the app `origin` to your pod in `trusted apps`
If you are using `https://bourgeoa.solidcommunity.net/public/tiddlywiki/` then : 
- the app origin is : `https://bourgeoa.solidcommunity.net` with no "/" at end
- got to your pod, connect and goto `preferences` `trusted applications` there you can add the app origin. Give at least `Read Write` rights. This being a test server I usually give all rights, which I know is too much in this case. This app do not manage .acl for the time being, may be in the future.

Hope the explanations are enough.

>Error saved tiddler : SFCFetchError: SFCFetchError 404 https://yala.solidcommunity.net/public/tiddlers/main/ - The requested resource could not be found

The message is not the good one. This is just saying that you and/or the app are not allowed to `write`. See above

>When saving GettingStarted with my details, it throws a red modal that reads
>
>>Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: path is undefined

I did not test it. Anyway if you change the parameters it is for the app and you do not have `write` authorization on my pod.

If you want your own copy of the tiddlywiki app, it can be done with solid-ide, the process is something like : 
- goto a `solid-ide` app, for example : `https://jeff-zucker.github.io/solid-ide`
- in solid-ide type : `https://bourgeoa.solidcommunity.net/public/tiddlywiki/` you shall see a file `index.html`
- add app origin `https://jeff-zucker.github.io` to your pod with at least `Read Write`
- in solid-ide `options` 'login' as a write allowed user to the folder in your pod. Example `https://yala.solidcommunity.net/profile/card#me` 
- in solid-ide click on the file icon, in the popup menu select copyFile and add the destination folder `https://yala.solidcommunity.net/public/tiddlywiki/` and  dest file `index.html`
- click on go or copy (I don't remember) confirm and wait :  ..... it is a long process (the file is big for a web app), there will be a message when finished

If you try, tell me if you succeed or have problems.

**Comment by almereyda** [comment]
Thank you @bourgeoa , unfortunately I am not able to find this *trusted apps* section in my pod, my profile card or in the Solid documentation. It appears this functionality does not exist. Which surprises me, since this application makes the assumption this is being cared for before being run. Or would that mean that is an administration setting, and I need to run my own pod to add a trusted app?

Then it seems strange the app tries to write to your pod, while it's authenticated against mine and has the tiddlers folder present.

---

*Update:* https://github.com/linonetwo/solid-tiddlywiki-syncadaptor#if-you-can-not-access-private-resources brought me into the right direction, and now my pod also shows the title bar which was hidden for some reason before. There is a User Avatar menu that has the preferences, and in there are preferences where the trusted apps can be configured.

**Comment by almereyda** [comment]
As solidcommunity.net has been implemented for the popup, this issue can be closed.

I will try everything else later, to see how all that works out in the end.

**Comment by bourgeoa** [comment]
My box broke and I am waiting for a replacement
I shall come back to you
